// Optional secrets / bindings not declared as wrangler.jsonc vars.
// Merges with the Env generated by `npx wrangler types`.
interface Env {
  API_KEY?: string;
  CLEANER_URL?: string;
  WATERMARKS_SERVER_API_KEY?: string;
  CLEANER?: DurableObjectNamespace;
  // PUBLIC_UPLOADS is a wrangler.jsonc var, so `wrangler types` generates it
  // as a string literal ("true" / "false"). Declaring it here too would clash.
  /** Bound once the `queues` block in wrangler.jsonc is enabled. */
  CLEAN_QUEUE?: Queue<{ jobId: string }>;
}
