// Optional secrets / bindings not declared as wrangler.jsonc vars.
// Merges with the Env generated by `npx wrangler types`.
interface Env {
  API_KEY?: string;
  /** `wrangler secret put TURNSTILE_SECRET`. Unset = verification is a no-op. */
  TURNSTILE_SECRET?: string;
  CLEANER_URL?: string;
  WATERMARKS_SERVER_API_KEY?: string;
  CLEANER?: DurableObjectNamespace;
  // PUBLIC_UPLOADS is a wrangler.jsonc var, so `wrangler types` generates it
  // as a string literal ("true" / "false"). Declaring it here too would clash.
  // CLEAN_QUEUE now comes from `wrangler types` (the queues block is enabled),
  // so declaring it here too would clash.
}
