// Optional secrets / bindings not declared as wrangler.jsonc vars.
// Merges with the Env generated by `npx wrangler types`.
interface Env {
  API_KEY?: string;
  CLEANER_URL?: string;
  WATERMARKS_SERVER_API_KEY?: string;
  CLEANER?: DurableObjectNamespace;
}
